[build]
	publish = "_site"
	command = "npm run build"
	functions = "_functions"
[[redirects]]
  from = "/api/messages/*"
  to = "https://getmessages-11ty-blog-production.up.railway.app/api/messages/:splat"
  status = 200
  force = true
